version: '3'
services:
  mongo:
    image: mongo
    container_name: reactive-cloud-stream-sample.mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
      MONGO_INITDB_DATABASE: 'reactive-cloud-stream-sample'
  zk:
    image: confluentinc/cp-zookeeper:latest
    container_name: reactive-cloud-stream-sample.zk
    hostname: zk
    ports:
      - '22181:22181'
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: reactive-cloud-stream-sample.kafka
    hostname: kafka
    depends_on:
      - zk
    ports:
      - '9092:9092'
      - '19092:19092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zk:22181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka_manager:
    container_name: reactive-cloud-stream-sample.kafka_manager
    image: hlebalbau/kafka-manager
    depends_on:
      - kafka
    ports:
      - '9000:9000'
    environment:
      ZK_HOSTS: zk:22181
      APPLICATION_SECRET: '12345'
    command: -Dpidfile.path=/dev/null
